# Generated by Django 5.2.7 on 2025-10-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_serviceorder_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
