# Generated by Django 5.2.7 on 2025-11-07 05:30

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_alter_serviceorder_down_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
