# Generated by Django 5.2.7 on 2025-11-07 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_auto_20251107_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Name can only contain letters and spaces.')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener 10 dígitos.', regex='^\\\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener 10 dígitos.', regex='^\\\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Name can only contain letters and spaces.')]),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener 10 dígitos.', regex='^\\\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='brakes_status',
            field=models.CharField(choices=[('Good', 'Good'), ('Regular', 'Regular'), ('Bad', 'Bad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='electrical_system_status',
            field=models.CharField(choices=[('Good', 'Good'), ('Regular', 'Regular'), ('Bad', 'Bad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='engine_status',
            field=models.CharField(choices=[('Good', 'Good'), ('Regular', 'Regular'), ('Bad', 'Bad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='fluid_level_status',
            field=models.CharField(choices=[('Good', 'Good'), ('Regular', 'Regular'), ('Bad', 'Bad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='gas_level',
            field=models.CharField(choices=[('Empty', 'Empty'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('Full', 'Full')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='main_failure',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='order_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='other_details',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='remaining_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='suspension_status',
            field=models.CharField(choices=[('Good', 'Good'), ('Regular', 'Regular'), ('Bad', 'Bad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='tires_status',
            field=models.CharField(choices=[('Good', 'Good'), ('Regular', 'Regular'), ('Bad', 'Bad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='tuning_status',
            field=models.CharField(choices=[('Good', 'Good'), ('Regular', 'Regular'), ('Bad', 'Bad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='vehicle_motor_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='vehicle_plates',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='vehicle_serial_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
