# Generated by Django 5.2.7 on 2025-11-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0010_alter_sparepart_description_alter_sparepart_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='spare_parts/', verbose_name='Imagen'),
        ),
    ]
