# Generated by Django 5.2.7 on 2025-11-11 01:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0011_sparepart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Name can only contain letters and spaces.')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener 10 dígitos.', regex='^\\\\d{10}$')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario'),
        ),
    ]
