# Generated by Django 5.2.7 on 2025-11-11 02:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0012_alter_mechanic_email_alter_mechanic_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener 10 dígitos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener 10 dígitos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener 10 dígitos.', regex='^\\d{10}$')], verbose_name='Teléfono'),
        ),
    ]
