# Generated by Django 5.2.7 on 2025-11-11 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0015_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
