# Generated by Django 5.2.7 on 2025-11-10 20:20

from django.db import migrations

def populate_vehicle_data(apps, schema_editor):
    VehicleBrand = apps.get_model('catalogs', 'VehicleBrand')
    VehicleModel = apps.get_model('catalogs', 'VehicleModel')

    brands_and_models = {
        'Nissan': ['Sentra', 'March', 'Versa', 'V-Drive', 'Z', 'Kicks', 'Altima', 'Magnite', 'Frontier', 'X-Trail', 'NP300', 'Urvan', 'Leaf', 'Pathfinder'],
        'Chevrolet': ['Aveo', 'Cavalier', 'Onix', 'Blazer', 'Suburban', 'Tahoe', 'Captiva', 'Tracker', 'Traverse', 'Trax', 'Groove', 'S10 Max', 'Montana', 'Cheyenne', 'Colorado', 'Silverado', 'Tornado', 'Express', 'Corvette', 'Camaro', 'Bolt EUV'],
        'Volkswagen': ['Virtus', 'Polo', 'Jetta', 'Jetta GLI', 'GTI', 'Taos', 'Tiguan', 'Nivus', 'Taigun', 'Teramont', 'Cross Sport', 'Saveiro', 'Amarok', 'Caddy', 'Transporter', 'Crafter'],
        'Toyota': ['Yaris', 'Corolla', 'Camry', 'Prius', 'GR Yaris', 'Avanza', 'RAV4', 'Highlander', 'Sequoia', '4Runner', 'Raize', 'Corolla Cross', 'Sienna', 'Hilux', 'Tacoma', 'Tundra', 'Hiace', 'GR Supra'],
        'KIA': ['Sportage', 'Seltos', 'Sorento', 'Telluride', 'K3', 'K4', 'Rio', 'Forte', 'Niro', 'EV6'],
        'Mazda': ['Mazda2', 'Mazda3', 'CX-3', 'CX-30', 'CX-5', 'CX-50', 'CX-70', 'CX-90', 'BT-50', 'MX-5'],
        'Hyundai': ['Grand i10', 'HB20', 'Elantra', 'Creta', 'Creta Grand', 'Tucson', 'Santa Fe', 'Palisade', 'IONIQ 5'],
        'Ford': ['Territory', 'Explorer', 'Expedition', 'Bronco', 'Bronco Sport', 'Escape', 'Mustang', 'Mustang Mach-E', 'Ranger', 'Maverick', 'Lobo', 'F-150', 'F-250', 'Super Duty', 'Transit'],
        'MG': ['MG3', 'MG5', 'MG GT', 'MG7', 'ZS', 'HS', 'RX5', 'RX8', 'RX9', 'One', 'Marvel R', 'IM LS7', 'Cyberster'],
    }

    for brand_name, models in brands_and_models.items():
        brand, created = VehicleBrand.objects.get_or_create(name=brand_name)
        for model_name in models:
            VehicleModel.objects.get_or_create(brand=brand, name=model_name)

class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0016_delete_testmodel'),
    ]

    operations = [
        migrations.RunPython(populate_vehicle_data),
    ]