# Generated by Django 5.2.7 on 2025-10-29 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('vehicle_brand', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_color', models.CharField(max_length=30)),
                ('vehicle_serial_number', models.CharField(max_length=50)),
                ('vehicle_motor_number', models.CharField(max_length=50)),
                ('vehicle_plates', models.CharField(max_length=10)),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('mileage', models.IntegerField()),
                ('gas_level', models.CharField(max_length=20)),
                ('main_failure', models.TextField()),
                ('engine_status', models.CharField(max_length=20)),
                ('electrical_system_status', models.CharField(max_length=20)),
                ('brakes_status', models.CharField(max_length=20)),
                ('suspension_status', models.CharField(max_length=20)),
                ('fluid_level_status', models.CharField(max_length=20)),
                ('tires_status', models.CharField(max_length=20)),
                ('tuning_status', models.CharField(max_length=20)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_orders/')),
                ('warranty_included', models.BooleanField(default=False)),
                ('warranty_valid_from', models.DateField(blank=True, null=True)),
                ('warranty_valid_to', models.DateField(blank=True, null=True)),
                ('warranty_exception', models.CharField(blank=True, max_length=200, null=True)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.client')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.mechanic')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('has_item', models.BooleanField()),
                ('specification', models.CharField(blank=True, max_length=100, null=True)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='catalogs.serviceorder')),
            ],
        ),
    ]
